server:
  port: 9001
eureka:
  client:
    registerWithEureka: false #是否向注册中心注册自己,客户端[服务消费方]不需要注册到 Eureka,本身是消费者,已在启动类添加注解@EnableEurekaClient,所以只管调用即可
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
#应用名|实例名
spring:
  application:
    name: apiConsumer